# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AWxtv3BgHeM1evYwIlvr_3cfUpdeIYC0
"""

num=int(input('digite dinheiro(em dolar):'))
print('US${} = R${}'.format(num, num * 5,64))

base=float(input('digite um valor: '))
altura=float(input('digite um valor: '))
print('Area={}m²'.format(base*altura))
print('litro de tinta a se utilizar {:.2f} litros'.format(base*altura/2))

Valor=float(input('valor da peça de roupa: '))
print('A peça com 5% de desconto é R${:.2f}'.format(Valor-(Valor*0.05)))

Salario=float(input('digite seu salario:r$ '))
print('Novo salario R${:.2f}'. format(Salario+(Salario*0.15)))

import math
num=int(input('digite um numero '))
num2=int(input('digite um numero '))
print('A hipotenusa é {:.2f}'.format(math.hypot(num,num2)))

from math import sin,cos,tan,radians
Angulo=float(input('digite um valor em graus '))
seno=sin(radians(Angulo))
cosseno=cos(radians(Angulo))
tangente=tan(radians(Angulo))
print('seno é {:.2f}'.format(seno))
print('seno é {:.2f}'.format(cosseno))
print('tang é {:.2f}'.format(tangente))

import random
n1=str(input('digite um nome: '))
n2=str(input('digite um nome: '))
n3=str(input('digite um nome: '))
n4=str(input('digite um nome: '))
lista= [n1,n2,n3,n4]
escolhido= random.choice(lista)
print('o aluno escolhido foi {}'.format(escolhido))

import random
n1=str(input('digite um nome: '))
n2=str(input('digite um nome: '))
n3=str(input('digite um nome: '))
n4=str(input('digite um nome: '))
lista=[n1,n2,n3,n4]
random.shuffle(lista)
print('A ordem de apresentação será')
print(lista)

'''import pygame
pygame.init()
pygame.mixer.music.load
pygame.mixer.music.play
pygame.event.wait()'''

n=float(10**(-15))
print('{}'.format(n))

'''calcular velocidade'''
v0=float(input('digite velocidade inicial (em m/s) '))
a=float(input('digite a aceleração(em m/s²): ' ))
t=int(input('digite o tempo(em segundos): '))
V= v0 + (a * t)
print('O valor da velocidade é {}m/s'.format(V))
print('o valor da velocidade em {:.2f}km/h'.format(V * 3.6))

S0=float(input('Distancia inicial(m): '))
v=float(input('velocidade que se encontra(m/s): '))
t=int(input('tempo em segundos: '))
S= S0 + (v * t)
print('A distancia percorrida é {}m'.format(S))

S0=float(input('Distancia incial em metros: '))
V0=float(input('Velocidade inicial em m/s: '))
t=int(input('tempo em segundos: '))
a=float(input('aceleraçao em m/s²: '))
S= S0 + V0 * t + (a * t**2)/2
print('Distancia em mruv é {}m'. format(S))

'''calcular comprimento da circurferencia'''
from math import pi
R=float(input('Digite o raio: '))
C= 2*R*pi
print('A valor da circuferencia é {:.0f}'.format(C))

#calcular velocidade media
S=float(input('Distancia final em metros: '))
S0=float(input('Distancia inicial em metros: '))
T=int(input('tempo final: '))
T0=int(input('tempo inicial: '))
Vm=(S - S0)/(T - T0)
print('A velociade media é {:.2f}m/s'.format(Vm))
print('A velocidade em é {:.2f}km/h'. format(Vm * 3.6))

''' converter temperatura de c° para f°'''
c=float(input('temperatura em celsius: '))
f= c/5 * 9 + 32
k= c + 273
print('a temperatura em f° é {:.2f} , e a temperatura absoluta é {} kelvin'.format(f,k))

from os.path import split
frase=input('digite uma frase: ')
a=frase.upper()
b=frase.lower()
c=len(frase.split())
d=len(frase.strip())
print(a)
print(b)
print(c)
print(d)

nome=str(input('Digite seu nome completo: ')).strip()
print('Anasilando nome...')
print('Seu nome em maiusculas é {}'.format(nome.upper()))
print('Seu nome em minusulas é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count('  ')))
separa= nome.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))

num=int(input('Digite um numero: '))
u=num //1 % 10
d=num //10 % 10
c=num //100 % 10
m=num// 1000 % 10
print('Analisando o numero {} '.format(num))
print('Unidade: {}'.format(u))
print('dezena: {}'.format(d))
print('centena: {}'.format(c))
print('milhar: {}'.format(m))

cid=str(input('Informe o nome de uma cidade: ')).strip()
print(cid[0:5].upper() == 'SANTO')
print(cid[0:5].lower() == 'santo')

nome=str(input('Digite seu nome completo: ')).strip()
print('Seu nome tem silva? {}'.format('silva' in nome.lower()))

frase=str(input('Escreva uma frase: ')).upper().strip()
print('A frase poussui {} a'.format(frase.count('A')))
print('A primeira letra A apareceu na posiçao {}'.format(frase.find('A')+1))
print('A ultima letra A aprareceu na posição {}'.format(frase.rfind('A')+1))

n=str(input('Informe seu nome completo: ')).strip()
nome= n.split()
print('A primeiro nome é {}'.format(nome[0]))
print('Seu ultimo nome é {}'.format(nome[len(nome)-1]))

tempo=int(input('Quantos anos tem seu carro? '))
if tempo <= 3:
  print('Carro novo')
else: 
  print('Carro antigo')

from prompt_toolkit.shortcuts.progress_bar.base import E
n1=float(input('Digite a primeira nota: '))
n2=float(input('Digite a segunda nota: '))
m=(n1 + n2)/2
print('Sua média é {}'.format(m))
if m <=5:
   print('reprovado,ESTUDE MAIS!')
else:
   print('Parábens aprovado')
print('...fim...')

import random
a=str(input('Digite um numero: '))
n=['1','2','3','4','5']
p=random.choice(n)
if p==a:
   print('voce ganhou')
print('Esse é meu valor {}'.format(a))

from random import randint
from time import sleep
computador= randint(0, 5)
print('-=-'*20)
print('Vou pensar em um numero entre 0 e 5. Tente adivinhar...')
print('-=-'*20)
jogador=int(input('Em que número eu pensei? '))
print('PROCESSANDO...')
sleep(3)
if jogador==computador:
  print('PARABÉNS! Você conseguiu me vencer!')
else:
  print('Ganhei! Eu pensei no número {} e não no {}!'.format(computador,jogador))

v=int(input('Velocidade do carro em km/h: '))
if v<=80:
  print('Velocidade segura')
else:
  print('Velocidade acima do permitido multa de R${:.2f}'.format((v-80)*7))

n=int(input('Digite um numero qualquer: '))
resto= n%2
if resto == 0:
  print('O numero é par')
else:
  print('O número é impar')

d=float(input('Digite a distancia a ser percorrida em km: '))
if d<=200:
  print('Valor da passagem é R${:.2f}'.format(d*0.5))
else:
  print('Valor da passagem será de R${:.2f}'.format(d*0.45))

from datetime import date
ano=int(input('Informe o valor do ano: '))
if ano == 0:
 ano=date.today().year
if ano % 4 == 0 and ano % 100 !=0 or ano %400 == 0:
  print('O ano é bissexto')
else:
 print('O ano não é bissexto')

a=int(input('Informe um numero '))
b=int(input('Informe um numero '))
c=int(input('Informe um numero '))
menor=a
if b < a and b < c:
  menor = b
if c < a and c < b:
  menor = c
maior=a
if b > a and b > c:
  maior=b
if c > a and c > b:
  maior=c   
print('O menor valor é {}'.format(menor))
print('O maior valor é {}'.format(maior))

s=float(input('Valor do seu salario: '))
if s<=1250:
  print('Seu novo salario será de R${:.2f}'.format((s*0.15)+s))
else:
  print('Seu novo salario será de R${:.2f}'.format((s*0.1)+s))

a=float(input('Informe um numero '))
b=float(input('Informe um numero '))
c=float(input('Informe um numero '))
if a< b + c and b< a+ c and c< b+a:
  print('Os valores formam um triangulo')
else:
  print('Não forma um triangulo')